### ISSUE TITLE
Release 0.6 Checklist

### ISSUE THREAD

**Issue by goneall** [spdx/tools-java#4]
- [x] Create release for any dependent libraries which have changed ([Spdx-Java-Library](https://github.com/spdx/Spdx-Java-Library), [spdx-java-jackson-store](https://github.com/spdx/spdx-java-jackson-store), [spdx-java-rdf-store](https://github.com/spdx/spdx-java-rdf-store), [spdx-java-spreadsheet-store](https://github.com/spdx/spdx-java-spreadsheet-store), [spdx-java-tagvalue-store](https://github.com/spdx/spdx-java-tagvalue-store))
- [x] Update dependency versions in the pom.xml file
- [x] Update the version in the pom.xml file
- [x] Publish using the command `maven deploy` - this will deploy to the [bintray SPDX tools](https://bintray.com/spdx/spdx-tools)
- [x] Sync the bintray repo with Maven Central
- [x] Tag the repo with the release version
- [x] Publish the release on github
